apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: base-service
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: oms-container
          envFrom:
            - configMapRef:
                name: oms-configmap
          # start - load env from secrets
          env:
            # DB secrets
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: db-msql
                  key: hostname
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-msql
                  key: port
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-msql
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-msql
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-msql
                  key: password
            # Security secrets
            - name: SC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: security
                  key: username
            - name: SC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: security
                  key: password
          # end - load env from secrets
          image: IMAGE_PLACEHOLDER
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 150m
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
