apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oms
commonLabels:
  app: base-service
resources:
  - deployment.yml
  - ingress.yml
  - service.yml
  - config/autoscaling.yml
  - config/configmap.yml
  - config/namespace.yml
