version: "3.8"
# All service running under similiar composer
services:
  db_mysql:
    image: mysql:8.0.3
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'changeMe123'
      MYSQL_DATABASE: 'db-project-001'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'changeMe123'
    ports:
      - 3306:3306
      - 33060:33060
  adminer:
    image: dockette/adminer:latest
    restart: always
    ports:
      - 8082:80
    expose:
      - 80
    depends_on:
      - db_mysql

#  db_postgres:
#    image: postgres:10
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: changeMe123
#      POSTGRES_DB: mydb-dev
#  db_mongo:
#    image: mongo:3.6.2
#    restart: always
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: changeMe123

  redis:
    hostname: redis
    image: redis:alpine
    command: redis-server --requirepass changeMe123
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
  redis_commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=changeMe123
    ports:
      - 8081:8081
    depends_on:
      - redis

# Your Application service
#  appOmsSvc:
#    image: gcr.io/beda-testing-dev/oms/base-service:185ef6a-2008111032
#    restart: always
#    ports:
#      - 8080:8080
#    expose:
#      - 8080
#    environment:
#      APP_VERSION: '0.0.1-RC'
#      APP_ENV: 'development'
#      DB_HOSTNAME: 'http://dbMsq'
#      DB_PORT: '3306'
#      DB_DATABASE: 'db-project-001'
#      DB_USERNAME: 'root'
#      DB_PASSWORD: 'changeMe123'
#      CACHE_HOSTNAME: 'http://redis'
#      CACHE_PORT: '6379'
#      CACHE_PASSWORD: 'changeMe123'
#      SC_USERNAME: 'changeMe123'
#      SC_PASSWORD: 'changeMe123'
#      SVC_CASHIER: 'http://sameple'
#    depends_on:
#      - db_mysql
#      - redis

volumes:
  db_mysql: