version: "3.8"
# All service running under similar composer
services:
  # mongodb
  dbMongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeMe123

#  redis:
#    hostname: redis
#    image: redis:alpine
#    command: redis-server --requirepass changeMe123
#    volumes:
#      - $PWD/redis-data:/var/lib/redis
#      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
#    environment:
#      - REDIS_REPLICATION_MODE=master
#    ports:
#      - 6379:6379

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8085:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: changeMe123
